// <auto-generated />
using System;
using GETASIS_Muhasebe.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GETASIS_Muhasebe.DAL.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220916084135_xx")]
    partial class xx
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GETASIS_Muhasebe.Entities.Cari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiDairesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cari");
                });

            modelBuilder.Entity("GETASIS_Muhasebe.Entities.Doviz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kisa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doviz");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Türk Lirası",
                            Kisa = "₺"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Dolar",
                            Kisa = "$"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Euro",
                            Kisa = "€"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Altın",
                            Kisa = "Au"
                        });
                });

            modelBuilder.Entity("GETASIS_Muhasebe.Entities.Hesap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("AcilisBakiye")
                        .HasColumnType("float");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DovizId")
                        .HasColumnType("int");

                    b.Property<string>("IBAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sube")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DovizId");

                    b.ToTable("Hesap");
                });

            modelBuilder.Entity("GETASIS_Muhasebe.Entities.Odeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Alacak")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BelgeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Borc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CariId")
                        .HasColumnType("int");

                    b.Property<int>("HesapId")
                        .HasColumnType("int");

                    b.Property<int>("OdemeTipId")
                        .HasColumnType("int");

                    b.Property<int>("Silindi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("Tarih")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VadeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.HasIndex("HesapId");

                    b.HasIndex("OdemeTipId");

                    b.ToTable("Odeme");
                });

            modelBuilder.Entity("GETASIS_Muhasebe.Entities.OdemeTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OdemeTip");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Personel"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Cari"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Vergi"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Şahsi"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Diğer"
                        });
                });

            modelBuilder.Entity("GETASIS_Muhasebe.Entities.Hesap", b =>
                {
                    b.HasOne("GETASIS_Muhasebe.Entities.Doviz", "Doviz")
                        .WithMany()
                        .HasForeignKey("DovizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doviz");
                });

            modelBuilder.Entity("GETASIS_Muhasebe.Entities.Odeme", b =>
                {
                    b.HasOne("GETASIS_Muhasebe.Entities.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GETASIS_Muhasebe.Entities.Hesap", "Hesap")
                        .WithMany()
                        .HasForeignKey("HesapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GETASIS_Muhasebe.Entities.OdemeTip", "OdemeTip")
                        .WithMany()
                        .HasForeignKey("OdemeTipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cari");

                    b.Navigation("Hesap");

                    b.Navigation("OdemeTip");
                });
#pragma warning restore 612, 618
        }
    }
}
